export {
  setOnlineOverride,
  resetSyncEngine,
  onSyncChange,
  isOnline,
  ensureDeviceState,
  patchSyncState,
  getSyncSnapshot,
  syncStatusLabel,
  noteLocalMutation,
  scheduleSync,
  pullNow,
  pushDirty,
  countLocalSyncable,
  markAllLocalDirty,
  cloudLooksEmpty,
  isLocalJournalEmpty,
  isVirginLocalSeed,
  bootstrapFromCloudIfEmpty,
  discardVirginSeedIfCloudHasJournal,
  enableAndUploadLocalJournal,
  setSyncEnabled,
  isRestoreBlocked,
  syncNow,
  bindNetworkSync,
  getCachedCloudRecords,
  SCHEMA_VERSION,
} from "./sync-engine-impl.js";
